### ISSUE TITLE
Bug: server body is undefined

### ISSUE THREAD

**Issue by vladinator1000** [jacksloan/prisma-proxy#2]
Hey, I encountered a strange bug where the client would send a body but when I logged it at the server it would be undefined.

I ended up fixing it by setting up the client like this:

```ts
createFetchClient<PrismaClient>({
  baseUrl: 'http://localhost:3333',
  fetch: (requestInfo, requestInit) => {
    return fetch(requestInfo, {
      ...requestInit,
      body: JSON.stringify(requestInit?.body),
      headers: {
        'Content-Type': 'application/json',
      },
    })
  },
})
```

And the server like this:
```ts
const app = express()
app.use(express.json())
const prisma = new PrismaClient()

createPrismaExpressProxy({
  app,
  prisma,
  middleware: {},
  defaultMiddleware: (req, _res, next) => {
    const { body, params, url } = req
    console.log({ url, params, body })

    next()
  },
})
```

I have a fork with a potential fix to the bug if you'd like to have it upstream? Here's what it looks like
https://github.com/jacksloan/prisma-proxy/compare/main...vladinator1000:empty-body-bug?expand=1

**Comment by jacksloan** [comment]
Hey @vladinator1000, thanks for digging in and fixing that! Looks good to me - merged/published your changes

**Comment by jacksloan** [comment]
Fixed by https://github.com/jacksloan/prisma-proxy/pull/3
